"------------------------------------------------------------
" Vim-Plug
"
" Plugin manager for vim

" Specify a directory for plugins (for Neovim: ~/.local/share/nvim/plugged)
call plug#begin('~/.vim/plugins')

" Make sure you use single quotes

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
" Plug 'junegunn/vim-easy-align'

" Any valid git URL is allowed
" Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Multiple Plug commands can be written in a single line using | separators
" Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
" Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
" Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Using a non-master branch
" Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }

" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
" Plug 'fatih/vim-go', { 'tag': '*' }

" Plugin options
" Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }

" Plugin outside ~/.vim/plugged with post-update hook
" Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" Unmanaged plugin (manually installed and updated)
" Plug '~/my-prototype-plugin'

" Initialize plugin system
" call plug#end()


"------------------------------------------------------------
" Plugins

" Solarized colortheme
Plug 'altercation/vim-colors-solarized'
"let g:solarized_termcolors = 16
"let g:solarized_termtrans = 1

" Powerline status bar
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
let g:airline_theme='solarized_flood'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'default'

" File browsing in vim
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'preservim/nerdcommenter'
map <C-n> :NERDTreeToggle<CR>
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1
let g:NERDToggleCheckAllLines = 1

" Fuzzy file finder
Plug 'ctrlpvim/ctrlp.vim'

" Tagbar support
Plug 'majutsushi/tagbar'
nmap <F8> :TagbarToggle<CR>

" Tmux support
Plug 'edkolev/tmuxline.vim'
let g:tmuxline_powerline_separators = 1

" Virtualenv support
Plug 'jmcantrell/vim-virtualenv'

" Git support
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

" Auto complete with support for most programming languages
Plug 'Valloric/YouCompleteMe', {'do': 'python install.py --clang-completer --go-completer --java-completer --js-completer'}
let g:ycm_autoclose_preview_window_after_completion = 1

" Syntax checking
Plug 'vim-syntastic/syntastic'
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_w = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_enable_balloons = 1
let g:syntastic_aggregate_errors = 1

" Enable checkers for syntastic
let g:syntastic_python_checkers = ['python', 'flake8']

let g:syntastic_go_checkers = ['go', 'gofmt', 'golint']

let g:syntastic_java_checkers = ['javac']

let g:syntastic_c_checkers = ['gcc']
let g:syntastic_c_compiler_options = '-std=c99 -Wall -ansi -pedantic -D_BSD_SOURCE'
let g:syntastic_c_auto_refresh_includes = 1

let g:syntastic_yaml_checkers = ['yamllint']

let g:sysntastic_json_checkers = ['jsonlint']

let g:syntastic_markdown_checkers = ['mdl']

let g:syntastic_rst_checkers = ['rstcheck']

" Snippet engine. Works with YouCompleteMe
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
let g:UltiSnipsExpandTrigger = "<c-tab>"
let g:UltiSnipsJumpForwardTrigger = "<c-j>"
let g:UltiSnipsJumpBackwardTrigger = "<c-k>"
let g:UltiSnipsEditSplit="vertical"

" Rust support
Plug 'rust-lang/rust.vim', {'for': 'rust'}

" Highlights trailing whitespace in red. Fix it with :FixWhitespace
Plug 'bronson/vim-trailing-whitespace'

" Initialize plugin system
call plug#end()

" Used to disable deprecation warning when using vim + python3.7
if has("python3")
    silent! python3 1
endif

let g:python_host_skip_check = 1

"if has("nvim")
"    let g:python_host_prog = "~/.pyenv/versions/neovim2/bin/python"
"    let g:python3_host_prog = "~/.pyenv/versions/neovim3/bin/python"
"endif


"------------------------------------------------------------
" Color Schemes
"
" These optioins control the different colors displayed in vim

" Enable syntax highlighting
syntax on

" Set vim default color scheme to use colors better with dark background.
" Can also be "light" if a light background is used
set background=dark

" set the color pallet to 256. Some terminals may only support 88.
" Gnome-terminal supports 256 colors
set t_Co=256

" set the colorscheme vim uses
colorscheme solarized


"------------------------------------------------------------
" Features
"
" These options and commands enable some very useful features in Vim, that
" no user should have to live without.

" Set 'nocompatible' to ward off unexpected things that your distro might
" have made, as well as sanely reset options when re-sourcing .vimrc
set nocompatible

" Attempt to determine the type of a file based on its name and possibly its
" contents. Use this to allow intelligent auto-indenting for each filetype,
" and for plugins that are filetype specific.
filetype indent plugin on

" return to same spot in file when previously closed
if has("autocmd")
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Change cursor to vertical line in insert mode: for GNOME Terminal
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"


"------------------------------------------------------------
" Must have options
"
" These are highly recommended options.

" Vim with default settings does not allow easy switching between multiple files
" in the same editor window. Users can use multiple split windows or multiple
" tab pages to edit multiple files, but it is still best to enable an option to
" allow easier switching between files.
"
" One such option is the 'hidden' option, which allows you to re-use the same
" window and switch from an unsaved buffer without saving it first. Also allows
" you to keep an undo history for multiple files when re-using the same window
" in this way. Note that using persistent undo also lets you undo in multiple
" files even in the same window, but is less efficient and is actually designed
" for keeping undo history after closing Vim entirely. Vim will complain if you
" try to quit without saving, and swap files will keep you safe if your computer
" crashes.
set hidden

" Note that not everyone likes working this way (with the hidden option).
" Alternatives include using tabs or split windows instead of re-using the same
" window as mentioned above, and/or either of the following options:
" set confirm
" set autowriteall

" Better command-line completion
set wildmenu

" Show partial commands in the last line of the screen
set showcmd

" Highlight searches (use <C-L> to temporarily turn off highlighting; see the
" mapping of <C-L> below)
set hlsearch

" Modelines have historically been a source of security vulnerabilities. As
" such, it may be a good idea to disable them and use the securemodelines
" script, <http://www.vim.org/scripts/script.php?script_id=1876>.
" set nomodeline

" Turn spell checking on if the current file is a .tex document
" autocmd BufNewFile,BufRead *.tex set spell spelllang=en_us


"------------------------------------------------------------
" Usability options
"
" These are options that users frequently set in their .vimrc. Some of them
" change Vim's behaviour in ways which deviate from the true Vi way, but
" which are considered to add usability. Which, if any, of these options to
" use is very much a personal preference, but they are harmless.

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" Show matching brackets.
set showmatch

" Incremental search
set incsearch

" Automatically save before commands like :next and :make
set autowrite

" Allow backspacing over autoindent, line breaks and start of insert action
set backspace=indent,eol,start

" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent

" Stop certain movements from always going to the first character of a line.
" While this behaviour deviates from that of Vi, it does what most users
" coming from other editors would expect.
set nostartofline

" Display the cursor position on the last line of the screen or in the status
" line of a window
set ruler

" Always display the status line, even if only one window is displayed
set laststatus=2

" Instead of failing a command because of unsaved changes, instead raise a
" dialogue asking if you wish to save changed files.
set confirm

" Use visual bell instead of beeping when doing something wrong
set visualbell

" And reset the terminal code for the visual bell. If visualbell is set, and
" this line is also included, vim will neither flash nor beep. If visualbell
" is unset, this does nothing.
set t_vb=

" Enable use of the mouse for all modes
" set mouse=a

" Set the command window height to 2 lines, to avoid many cases of having to
" "press <Enter> to continue"
set cmdheight=2

" Display line numbers on the left
set number

" Quickly time out on keycodes, but never time out on mappings
set notimeout ttimeout ttimeoutlen=200

" Use <F11> to toggle between 'paste' and 'nopaste'
set pastetoggle=<F11>

" Use UTF-8 encoding
set encoding=utf-8

" Use the system clipboard
if has("nvim")
    set clipboard=unnamedplus
else
    set clipboard=unnamed
endif


"------------------------------------------------------------
" Indentation options
"
" Indentation settings according to personal preference.

" Indentation settings for using 4 spaces instead of tabs.
set tabstop=8
set shiftwidth=4
set softtabstop=4
set expandtab
set shiftround

" Indentation settings for using hard tabs for indent. Display tabs as
" two characters wide.
"set shiftwidth=4
"set tabstop=4


"------------------------------------------------------------
" Mappings
"
" Useful mappings

" Set leader to space
let g:mapleader = "\<Space>"

" Map Y to act like D and C, i.e. to yank until EOL, rather than act as yy,
" which is the default
map Y y$

" Map <C-L> (redraw screen) to also turn off search highlighting until the
" next search
nnoremap <C-R> :nohl<CR><C-L>

" easier navigation between splits
nnoremap <Leader>j <C-W><C-J>
nnoremap <Leader>k <C-W><C-K>
nnoremap <Leader>l <C-W><C-L>
nnoremap <Leader>h <C-W><C-H>

" Save a file with <Leader>w (<Space>w)
nnoremap <Leader>w :w<CR>
nnoremap <Leader>q :wq<CR>
nnoremap <Leader>e :q!<CR>

" Use leader to open a file
nnoremap <Leader>o :CtrlP<CR>

" Copy and paste shortcuts to use system clipboard
"map y "+y
"map d "+d
"map p "+p
"map P "+P
"map p "+p
"map P "+P

" Enter visual mode easy
nmap <Leader><Leader> V

tnoremap <ESC> <C-\><C-n><CR>

"------------------------------------------------------------
" FileTypes
"
" Set different settings for different filetypes
" sw=shiftwidth, sts=softtabstop, et=expandtab

autocmd BufReadPost *.env set filetype=sh
autocmd BufReadPost *.tf set filetype=go
autocmd BufReadPost *.tpl set filetype=sh
autocmd BufReadPost Dockerfile* set filetype=dockerfile
autocmd BufReadPost Vagrantfile* set filetype=ruby

autocmd FileType make set noexpandtab " make files need hard tabs, not spaces
autocmd FileType html setl sw=2 sts=2 et
autocmd FileType yaml setl sw=2 sts=2 et
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
